name: Metrics generator

on:
  schedule:
    - cron: '0 4 * * MON'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install github-metrics

      - name: Run metrics
        run: python run.py
        env:
          GITHUB_LOGIN: ${{ secrets.LOGIN }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          ORG_NAME: ${{ secrets.ORG_NAME }}
          REPOSITORY_NAME: ${{ secrets.REPOSITORY_NAME }}
      - name: Export Dashboard
        run: python export.py

      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
